name: test matrix
on: push
jobs:
  build:
     if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
     strategy:
       fail-fast: false
       matrix:
         os: [ubuntu-latest, macos-latest]
     runs-on: ${{ matrix.os }}    
       
    #steps:
      #- uses: actions/checkout@v1
      #- run: echo ${{matrix.TARGET}}
     steps:
        # Steps represent a sequence of tasks that will be executed as part of the job
       - name: Checkout repo content 
         #uses: actions/checkout@v2 # checkout the repository content to github runner.
         uses: actions/checkout@master
        
       - name: Say Something
         run: |
           echo "Hello ${message}"
           echo "Again Welcome"
           echo $PATH
           echo $PWD
         shell: bash
       - name: Set up Python 3.x
         uses: actions/setup-python@v2
         with:
           python-version: 3.9
        #run: echo "Welcome to the NEST static analysis build"
         env:
           key: xNEST_BUILD_TYPE= STATIC_CODE_ANALYSIS
       - name: Install dependencies
         #uses: actions/cache@master
         run: |
            python -m pip install --upgrade pip setuptools
            python -m pip install scipy junitparser numpy nose cython matplotlib terminaltables coreutils
            pip list
            g++ --version
            set -o pipefail
            chmod +x extras/staticbuild.sh
            ./extras/staticbuild.sh
